#!/usr/bin/php

<?php

$GLOBALS['startime'] = microtime(true);

use Libraries\Console\Console;

require_once(
    __DIR__ . DIRECTORY_SEPARATOR .
    'core' . DIRECTORY_SEPARATOR .
    '_bootstrap.php'
);

$console = new Console();
$console->run();